fix(conf): update scalingo-22 and zlib version
Scalingo/php-buildpack pull request #287
Opened 2023-01-03 10:38 UTC by curzolapierre

2023-01-08 18:27 UTC, Soulou commented on bin/compile
> +if [ -n "$DEBUG" ]; then
```suggestion
if [ -n "$BUILDPACK_DEBUG" ]; then
```

2023-01-08 18:29 UTC, Soulou commented on bin/compile
> +if [ -n "$DEBUG" ]; then
Already present here: https://github.com/Scalingo/php-buildpack/blob/d560c1a1934daca2cfbbc8ef5af810e79d7488f5/bin/compile#L24-L26

2023-01-08 18:32 UTC, Soulou requested changes

2023-01-08 18:32 UTC, Soulou commented on bin/compile
> +if [ "$(php_api_version)" = "20170718" -o "$(php_api_version)" = "20180731" -o "$(php_api_version)" = "20190902" ] ; then
Condition is not understandable, make a helper function.

2023-01-08 18:32 UTC, Soulou commented on bin/compile
> +if [ "$(php_api_version)" = "20170718" ] ; then
Semantic is not clear, make a helper function

2023-01-09 14:28 UTC, SCedricThomas commented
Why do we include PHP 7.3 for mcrypt bundling as it is no longer available as a standard php extension: 
https://www.php.net/manual/en/mcrypt.installation.php 
https://github.com/Scalingo/php-buildpack/blob/dd52e9fae2da9708b94844400661d64a17eabaea/bin/compile#L343-L346

2023-01-09 15:29 UTC, Soulou commented
If deployments work for scalingo-22 and the different php version, LGTM

2023-01-17 15:49 UTC, merged